### ISSUE TITLE
hasChannel not properly checking adhoc channels registered by another loader

### ISSUE THREAD

**Issue by pupnewfster** [neoforged/NeoForge#1051]
**Minecraft Version:** 1.20.6

**NeoForge Version:**  20.6.99-beta

**Steps to Reproduce:**
 1. Launch a neo server
 2. Have a fabric client connect to the server
 3. Have the server check if the client has a custom network channel that was registered by fabric as an adhoc channel.

**Description of issue:**

When checking if a connection has a channel (at least on a server), it always returns false if the other end is providing it as an adhoc channel by means of the [`NetworkRegistry#onMinecraftRegister`](https://github.com/neoforged/NeoForge/blob/65e8748fc6ce6cf2b5b06b6e7943beabf269a247/src/main/java/net/neoforged/neoforge/network/registration/NetworkRegistry.java#L688). I believe this is because in `NetworkRegistry#initializeOtherConnection` we initialize [`ATTRIBUTE_PAYLOAD_SETUP` to `NetworkPayloadSetup.empty()`](https://github.com/neoforged/NeoForge/blob/65e8748fc6ce6cf2b5b06b6e7943beabf269a247/src/main/java/net/neoforged/neoforge/network/registration/NetworkRegistry.java#L392). And then when we end up querying `NetworkRegistry#hasChannel` we skip checking the adhoc channels because [`payloadSetup` is nonnull](https://github.com/neoforged/NeoForge/blob/65e8748fc6ce6cf2b5b06b6e7943beabf269a247/src/main/java/net/neoforged/neoforge/network/registration/NetworkRegistry.java#L600-L602)

**Comment by Shadows-of-Fire** [comment]
I don't think this is the case.  We don't skip querying ad-hoc channels if the payload setup is present, rather we skip querying the payload setup if it is absent.  We _always_ fall back to the ad-hoc channels if we don't find it in the payload setup.
```java
        NetworkPayloadSetup payloadSetup = connection.channel().attr(ATTRIBUTE_PAYLOAD_SETUP).get();
        if (payloadSetup == null) {
            return getKnownAdHocChannelsOfOtherEnd(connection).contains(payloadId);
        }

        // If a protocol is specified, only check against channels for that protocol
        // Otherwise check against all protocols.
        if (protocol != null && payloadSetup.getChannels(protocol).containsKey(payloadId)) {
            return true;
        } else if (protocol == null && payloadSetup.channels().values().stream().anyMatch(map -> map.containsKey(payloadId))) {
            return true;
        }

        return getKnownAdHocChannelsOfOtherEnd(connection).contains(payloadId);
```

I do know there is the potential for a race condition against `minecraft:register` being received early in the play phase, which will prevent sending / receiving payloads since we require `hasChannel` returns true before allowing a payload to be sent. 

There are two options to fix that:
1. Stop checking `hasChannel` on send. Maybe we could only do this if the connection type is `OTHER` due to the race condition, since `NEOFORGE` connections shouldn't be relying on ad-hoc channels anyway.
2. Figure out a common payload registration scheme so that all registrations can be declared in the configuration phase, avoiding the race during the play-phase transition.
