### ISSUE TITLE
The “Console Tooltips” resource pack does not work as expected, characters are not rendered correctly.

### ISSUE THREAD

**Issue by Lolothepro** [neoforged/NeoForge#1080]
**NeoForge Version:** 20.6.113-beta/1.21-pre4

**Steps to Reproduce:**
 1. Install [this](https://modrinth.com/resourcepack/console-tooltip) resource pack
 2. Check the broken rendering of item tooltips

**Description of issue:**

The “Console Tooltips” resource pack does not work as expected, characters are not rendered correctly.

With Creative mode:

Vanilla:
![2024-06-09_21 31 30](https://github.com/neoforged/NeoForge/assets/68275908/952071ec-aef5-4856-a899-fb8faa15561d)

NeoForge:
![2024-06-09_21 29 09](https://github.com/neoforged/NeoForge/assets/68275908/70133399-213f-47e5-8092-c559ffebf846)

With Survival mode:

Vanilla:
![2024-06-09_21 35 15](https://github.com/neoforged/NeoForge/assets/68275908/e612b216-548b-42aa-9f36-3b1dcddaf2fe)

NeoForge:
![2024-06-09_21 35 19](https://github.com/neoforged/NeoForge/assets/68275908/e701bf96-20a0-4a7f-a23e-b0ef03a57939)

**Comment by XFactHD** [comment]
NeoForge patches tooltip rendering to allow using a color gradient for the background rectangle:
https://github.com/neoforged/NeoForge/blob/a8d9b4775ef5a452b5ed0a27622a2fe7f59f3b57/patches/net/minecraft/client/gui/screens/inventory/tooltip/TooltipRenderUtil.java.patch#L36-L48
`GuiGraphics#fill()` (used by vanilla for the background) applies incorrect coordinate mirroring (a given axis is mirrored if the start coordinate is smaller than the end coordinate instead of the other way round) while `GuiGraphics#fillGradient()` (used by the patch) does not apply any coordinate mirroring. This means that the shader to relies on technically incorrect vertex positions when it applies a padding to make the tooltip larger, causing the padding to have the exact opposite effect when used with the NF patch.

Fixing it would mean either breaking the gradient feature or risking that the bug reappears somewhere else. For that reason and also the fact that replacing core shaders is not officially supported by vanilla, I will close this as wontfix for the time being.
