### ISSUE TITLE
[1.21] Context regression for `IBlockExtension#getExpDrop`

### ISSUE THREAD

**Issue by Tslat** [neoforged/NeoForge#1101]
As of 1.21, there is no longer a way for a block to customise its own XP drop amount with relevance to silk touch or fortune, without hooking an event listener for itself.

IBlockStateExtension#getExpDrop has lost its overload with the two relevant integers, and does not appear to have a replacement with ITemStack context

**Comment by Shadows-of-Fire** [comment]
I have a todo note to add the additional context available to `getExpDrop` (it should have everything available in the `BlockDropsEvent`).  

However, the way vanilla handles experience for Silk Touch is different from the prior versions. Instead of the block specifying that it doesn't drop XP when silk touch is present, Silk Touch uses the `minecraft:block_experience` enchantment effect to set the dropped experience to zero.

Fortune doesn't change the amount of dropped experience, though if you wanted to make a block drop more experience under fortune, the context will be necessary.
