### ISSUE TITLE
1.21: Efficiency enchantment has no effect on vanilla tools

### ISSUE THREAD

**Issue by legobmw99** [neoforged/NeoForge#1120]
**Minecraft Version:** 1.21

**NeoForge Version:** 21.0.10

**Steps to Reproduce:**
 1. Give yourself a golden shovel
 2. Enchant with efficiency 5
 3. Observe that mining dirt is not instant

**Comment by sciwhiz12** [comment]
Confirmed on 21.0.10-beta. 

In 1.20.5, PR #850 modified the `ItemStack#forEachModifier` method to short-circuit and call a newly-added extension method `IItemStackExtension#getAttributeModifiers`. 

However, in 1.21, the `forEachModifier` method was changed to also have the responsibility of calling `EnchantmentHelper#forEachModifier`, which is responsible for applying the attribute modifying effects of enchanments. 

Because of the short-circuiting in `forEachModifier` (the `EquipmentSlot` variant), the enchantment-based modifiers never get applied properly. To confirm the bug, I removed that patch to `ItemStack#forEachModifier` locally, and that fixes the behavior of the enchantments.

The simple solution seems to be changing the short-circuiting `if (true) return` to an `if (false) { ... }` that covers the code replaced by the `getAttributeModifiers(...).forEach(...)` call. 

However, that brings up the fact that the `EquipmentSlotGroup` variant of `forEachModifier` is not patched. To fix that, however, would require reworking of `ItemAttributeModifierEvent` to work with both `EquipmentSlot`s and `EquipmentSlotGroup`s, which I leave to someone else with knowledge on attribute modifiers to do if they are able.

For now, the simple solution should suffice to fix this bug, and another contributor can work on refactoring the modifiers event to encompass `EquipmentSlotGroup`s.
