### ISSUE TITLE
[Feature] Datapack Registry Callbacks

### ISSUE THREAD

**Issue by frqnny** [neoforged/NeoForge#1158]
Unless I am mistaken, there currently is no way to modify datapack registries in the API. I'm wondering if its planned or if its in the works?

**Comment by ChampionAsh5357** [comment]
Could you provide more information? What do you mean by 'modify data registries'? Like add entries to it? Modify existing objects like biomes? Something else entirely?

**Comment by frqnny** [comment]
I believe the 1.20.2 Registry Rework has a ModifyRegistryEvent that only applies to Builtin Registries. In that event, you can add a callback to each time an object is added to that registry. 

It would be particularly useful to do so with datapack registries, as the hook for that is particularly more hidden and should be handled by the API.

**Comment by frqnny** [comment]
https://github.com/neoforged/NeoForge/pull/257#discussion_r1392785646

Found some discussion around it being done at a later date according to this comment in the PR.

**Comment by ChampionAsh5357** [comment]
Ah, I'm guessing that's because the datapack registries are added during level load. I don't see any difficulty in adding another event around where `RegistryDataLoader.RegistryData#create` is called, assuming that the `WritableRegistry` doesn't get overridden later in the pipeline.

Someone just needs to create the PR for it.

**Comment by Shadows-of-Fire** [comment]
What functionality would you need that requires to react to parsing of datapack registry entries at registration that could not be accomplished via reload listener?
