### ISSUE TITLE
ConcurrentModificationException Error on Launch/Load

### ISSUE THREAD

**Issue by nickkeane** [neoforged/NeoForge#1169]
**Minecraft Version:**
1.21

**NeoForge Version:**
21.0.29-beta

**Logs:**
https://mclo.gs/RKw2IGO

**Steps to Reproduce:**
Launch Minecraft NeoForged from Prism Launcher

**Description of issue:**
Inconsistently when I launch my setup, I get a ConcurrentModificationException and minecraft crashes to desktop. This doesn't always happen, sometimes it works and gets to the main menu without issue.

**Comment by XFactHD** [comment]
From a quick code review this is very unlikely to be a NeoForge issue. Can you reproduce this without any mods?

**Comment by sciwhiz12** [comment]
Something is adding a client-side reload loader while a reload is already occurring. That should be impossible if all mods adds a reload loader through `RegisterClientReloadListenersEvent`, which is the only supported way.

As this is not an issue with NeoForge but instead a badly-behaving mod (which cannot be determined), I'm closing this issue. You may try to do a binary search -- cutting the amount of mods in half until the issue disappears, then trying the other half; continuing until you find the mod(s) responsible -- to narrow down the culprits, but otherwise we can't really help in this.
