### ISSUE TITLE
EntityEvent.Size#setNewSize(x, true) doesn't set new eyeheight properly (regression)

### ISSUE THREAD

**Issue by HenryLoenwind** [neoforged/NeoForge#1170]
https://github.com/neoforged/NeoForge/blame/412c6ab06e5457de8f08e15e03cc07266306786a/src/main/java/net/neoforged/neoforge/event/entity/EntityEvent.java#L169

The `this.newSize` got lost. That way the new size isn't taken into account when setting the eye height as promised by the javadoc.

```java
this.newEyeHeight = this.getEntity().getEyeHeightAccess(this.getPose());
```

was:

```java
this.newEyeHeight = this.getEntity().getEyeHeightAccess(this.getPose(), this.newSize);
```

PS: Regression of this https://github.com/neoforged/NeoForge/commit/53c039680c356062c870b1c9ed321481812a944e

**Comment by sciwhiz12** [comment]
Based on an investigation of the code, the `EntityDimensions` now holds the eye height of the entity, rather than being separate as it was in the past (which is why we have that accessor for `getEyeHeight(Pose, EntityDimensions)`).

As such, `EntityEvent.Size` should be refactored to remove the eye height setter and getter, as callers can adjust the eye height in the `EntityDimensions` they set on the event.
