### ISSUE TITLE
Cant add control of Structure spawning to configs.

### ISSUE THREAD

**Issue by Kettle5000** [neoforged/NeoForge#1205]
Why is it no longer possible to control structure spawning and allow players to use config files to activate/deactive them, check for dimension (NOT BIOME). 
Right now in 1.20.4 forge im completely unable to modify structure generation in this way, specially since there are modded dimensions that use vanilla biomes and generation. 
I sadly ask here for help since i cant find any possible solution for this, but i noticed that in older versions of forge it used to be possible to even remove vanilla structure generation for specific dimensions. 
If there is already a solution for this please tell me since i cant find a single event to achieve this.

**Comment by TelepathicGrunt** [comment]
This wasn't a Forge or NeoForge change. This was a Mojang change. 1.18.2 changed how structures work and 1.19.2 did it again.

The way the current system works is that structures aren't tied to dimensions at all. They are tied to biomes. The structure sets for the structure is now parsed by Minecraft and added to every dimension's chunk generator if that dimension has at least one of the structure's valid biome in the dimension biome source's PossibleBiomes field.

Even worse, the structure set given to each chunk generator is the same instance so you can't just modify the structure set for one dimension without affecting all. You physically can't easily lock certain structures to certain dimension. If you add a dimension check to the StructureType class, the locate command and any locating method call will think the structure can spawn in the dimension due to structure set existing and will check something like 40000 chunks for the structure. Lag or deadlocks the world.

So here is my suggestion, ignore the dimension. Keep the structure locked into the biome you want. Any modded or datapack dimension should be using their own biomes anyway.

Think of it like features or mobs. You wouldn't expect a Jungle biome on Jupiter dimension to suddenly be missing giant trees and no Ocelots. In fact, people would complain that the biome is having different behaviors in different dimensions. A biome should behave exactly the same no matter where it spawns. And this includes structures as well as structures are a part of what that biome is. So that Jupiter dimension should be using its own jungle biome variant. Something like JupiJungle Biome where they copy most features and mobs and structures of the vanilla biome but omit other stuff. Then players and pack makers can override the biome tag on the structure to leave out JupiJungle so it does not spawn there if desired.

**Comment by TelepathicGrunt** [comment]
To be clear for anyone else wondering how structures are configured as of 1.18.2+, it's JSON files. Meaning, you make datapacks. Not configs. It's all handled by vanilla. Yep, vanilla has fully datadriven structures.

So if you want to remove the structure from a biome, you would override this tag or line and have to point to a tag without the biome you want. (Technically, you could also do the holderset operations Neo added here to do a tag minus one entry but that's more obtuse)
https://github.com/TelepathicGrunt/StructureTutorialMod/blob/211c5cdfb2e97a3a111df8aaba7697d409c38316/src/main/resources/data/structure_tutorial/worldgen/structure/json_only_house.json#L16

If one want's to turn off a structure completely, they would remove the structure entry from the structure set (They can also change structure spawn rate here with spacing and separation values)
https://github.com/TelepathicGrunt/StructureTutorialMod/blob/211c5cdfb2e97a3a111df8aaba7697d409c38316/src/main/resources/data/structure_tutorial/worldgen/structure_set/json_only_house.json#L5-L8

There is nothing here about dimensions because Minecraft reads the file and injects the structure set to all relative chunk generators. Mojang went hard on tying the structure to the biomes and crippled any dimension checking abilities to the point it is far too unsafe to do so without accidentally causing 40000 chunks checking on a locate call. Again, dimensions should be using their own biomes if they should not have the structures from the original biome.

**Comment by Kettle5000** [comment]
Oh this is very sad
Lost Cities was one of my favorites mods but knowing this I think its just impossible (not tried mixins yet) 
I will try to check a way to copy paste features from vanilla biomes to apply them on this dimensions as a possible solution. 
Hope they change this some day.
Just to take the last hope but can this be achieved using mixins?

**Comment by TelepathicGrunt** [comment]
Almost anything can be done with mixins. The question is if the person writing the mixin knows exactly what they are doing, writes mixin without blowing anything else up, understands how dynamicregistries work to make sure they don't cause unregistered element issues, etc. I kind of know a spot where mixin to not spawn a structure for a dimension could work but I would not trust myself to write said code and I am too afraid of unforeseen consequences.

Lost Cities could try making a dimension that clones the overworld biomes into new biome instances, registers them, and uses those for its dimensions. But without more details, we don't know exactly what you are trying to do with Lost Cities. Have you talked to the Lost Cities dev? They may have enough control over their own chunk generator to handle structures toggling safely as they can manipulate the structure locating methods in the Lost City dimension's chunk generator

**Comment by Kettle5000** [comment]
No, he is having the same trouble. Even worst, villages are causing havoc upon cities generation, which leads to cities abruptly ending when a village is generated, and if you try to add extra mods, all of those structures spawn there and also conflict with it.
I already tried to use mixins but sadly im very unexperienced in the field since im not even a coder, i do this for a hobby.
I will try to learn more about it an hoping to not break stuff. 
I already tried to modify the class StructureChecker#canCreateStructure method by injecting a custom logic to check the dimension but it didnt even fire. Which either is me not installing mixins well or just the method never being called.
Still I would like to know where do you think a mixin could be applied to minimize the possible damage. 
Many thanks in advance.

**Comment by McJty** [comment]
> Oh this is very sad Lost Cities was one of my favorites mods but knowing this I think its just impossible (not tried mixins yet) I will try to check a way to copy paste features from vanilla biomes to apply them on this dimensions as a possible solution. Hope they change this some day. Just to take the last hope but can this be achieved using mixins?

Lost Cities doesn't use structures at all. It has its own system Also Lost Cities is already on 1.21

**Comment by Kettle5000** [comment]
> > Oh this is very sad Lost Cities was one of my favorites mods but knowing this I think its just impossible (not tried mixins yet) I will try to check a way to copy paste features from vanilla biomes to apply them on this dimensions as a possible solution. Hope they change this some day. Just to take the last hope but can this be achieved using mixins?
> 
> Lost Cities doesn't use structures at all. It has its own system Also Lost Cities is already on 1.21

oh did you manage to fix the issue of villages spawning in and structures from other mods ?

**Comment by McJty** [comment]
> > > Oh this is very sad Lost Cities was one of my favorites mods but knowing this I think its just impossible (not tried mixins yet) I will try to check a way to copy paste features from vanilla biomes to apply them on this dimensions as a possible solution. Hope they change this some day. Just to take the last hope but can this be achieved using mixins?
> > 
> > 
> > Lost Cities doesn't use structures at all. It has its own system Also Lost Cities is already on 1.21
> 
> oh did you manage to fix the issue of villages spawning in and structures from other mods ?

No I didn't but that has always been a thing. I haven't been actively looking into this though

**Comment by Kettle5000** [comment]
> > > > Oh this is very sad Lost Cities was one of my favorites mods but knowing this I think its just impossible (not tried mixins yet) I will try to check a way to copy paste features from vanilla biomes to apply them on this dimensions as a possible solution. Hope they change this some day. Just to take the last hope but can this be achieved using mixins?
> > > 
> > > 
> > > Lost Cities doesn't use structures at all. It has its own system Also Lost Cities is already on 1.21
> > 
> > 
> > oh did you manage to fix the issue of villages spawning in and structures from other mods ?
> 
> No I didn't but that has always been a thing. I haven't been actively looking into this though

I have been trying to fix this for a while now, thats why i asked you in an old issue in your Mod github if you tried mixins, i will keep looking into this if i find any solution i will try to reach you
for now i think this has no solution.

**Comment by sciwhiz12** [comment]
Based on @TelepathicGrunt's comments and further discussion, we can't do anything more here, as Mojang's changes to structure spawning tied it almost irrevocably to biomes rather than dimensions.  Closing.
