### ISSUE TITLE
re-add or remove the ‘PalettedContainer.java.patch’ file

### ISSUE THREAD

**Issue by Lolothepro** [neoforged/NeoForge#1321]
Minecraft : 1.18  - 1.21

https://github.com/neoforged/NeoForge/blob/1.20.1/patches/minecraft/net/minecraft/world/level/chunk/PalettedContainer.java.patch

https://github.com/neoforged/NeoForge/blob/1.21.x/patches/net/minecraft/world/level/chunk/PalettedContainer.java.patch

The latest working version of the patch is for Minecraft 1.17.x
https://github.com/MinecraftForge/MinecraftForge/blob/1.17.x/patches/minecraft/net/minecraft/world/level/chunk/PalettedContainer.java.patch

This file doesn't seem to have changed since Minecraft 1.18, is it possible to do something to re-add it (or delete it)?

**Comment by TelepathicGrunt** [comment]
Closing this as we are going to handle cleaning up TODO as its own work effort. If we had an issue report for every todo, we would have over 70 new issue reports which isn't sustainable and causes more work than necessary.
![image](https://github.com/user-attachments/assets/5a408f80-cc07-4623-90aa-7ef3817f4cc6)

If there is an actual tangible issue stemming from a todo, like an unpatched bug or a recent regression of a feature that a modder needs right now, then an issue report can be made to prioritize it. Otherwise, we will get to these various todos on our own time. Right now, we got bigger fish to fry first than to analyze every todo at the moment.
