### ISSUE TITLE
Should `c:tools/melee_weapon` contain Hoes, Pickaxes, and Shovels? (Maybe Trident too)

### ISSUE THREAD

**Issue by TelepathicGrunt** [neoforged/NeoForge#1327]
Someone brought up that the melee weapon tag inherited from Fabric API's past only contains Swords, Axes and Maces by default.
https://github.com/FabricMC/fabric/blob/1.21/fabric-convention-tags-v2/src/generated/resources/data/c/tags/item/tools/melee_weapon.json

Should this be changed to also have Hoes, Shovels, and Pickaxes? Specifically, any tool that has an ATTACK_DAMAGE attribute? (Maybe paired with ATTACK_SPEED attribute too?) Might also mean we should add Trident to it as it can be used both ranged and melee. 

If not, what would be a better way to describe this tag to someone to make it clear that only Swords, Axes, and Maces belong in this tag? Like weapons that are a viable melee weapon where being up close with physical attacks is the main attacking method as oppose to throwing or attacking being a weak secondary use like shovels.

Fabric: https://github.com/FabricMC/fabric/issues/3949

**Comment by KnightMiner** [comment]
This is where you start running into challenges trying to define tool behavior with tags. Doing it in a third party means you are going based on secondhand knowledge of what people need.

In Tinkers Construct, I have tags for all my items that work as a weapon (determines which ones can receive bonus melee damage from modifiers and alike) and also a tag for weapons that are primarily a weapon (used for a small list of modifiers and prevents the tool taking double damage on melee attacks). I need that level of granularity, but not everyone needs that level and its a lot more work to maintain if you don't

Without the granularity you will either make the tag annoying for those who want "anything that can attack" or annoying for those who want "anything vanilla classifies as a weapon", which is also different from "anything that does not take double damage when attacking" and "anything that receives weapon enchantments in the enchanting table". I would try to poll people who are currently/want to use this tag as standards always should be defined by people using them (personally I don't benefit from these as I mostly use such tags for crafting and due to the way my API works I need too much control over the item class to apply it to some other mods item so I won't state an opinion on what it should do).

**Comment by RaymondBlaze** [comment]
I believe `c:tools/melee_weapon` should apply to any tool that contains `ATTACK_DAMAGE` and `ATTACK_SPEED` attributes (it's unlikely for them to only having one of them).
On the other hand, the `c:tools/mining_tools` (probably needs to be renamed to `c:tools/mining` instead) should apply to any tool whose mining speed is bigger than 1 for some or any blocks.
If we need more specific c tags for weapons and mining tools, we should create them with a more specific name instead of letting one of them dominate generic names like `melee_weapon` and `mining_tools`.
For specifying if a tool is primarily used for `something`, I suggest we use `c:tools/something/primary` for that, though I suppose there would be arguments about whether to put Axes in to `c:tools/melee_weapon/primary` ;)
