### ISSUE TITLE
Deprecate / remove share tag system

### ISSUE THREAD

**Issue by Technici4n** [neoforged/NeoForge#148]
The client is authoritative over the stacks in creative mode, so the full item stack data must always be synced to the client.

Some mods like Immersive Engineering use the share tag system to sync capability data to the client. This will not be necessary anymore after the capability rework (#73).

**Comment by pupnewfster** [comment]
The other use case of share tags is to send less data to the client so that packet limits aren't hit. And yes cloning the stack in creative will cause that data to be lost, but it is better than having the client crash. If we do end up removing it we likely will want to add a page to the docs about how to use WSD to offload bits of data from the item's nbt.
