### ISSUE TITLE
[Suggestion] Add Missing `c:tools/knife` item tag to the `c:tools` tags group

### ISSUE THREAD

**Issue by ffuentesm** [neoforged/NeoForge#1498]
Many mods add a knife to their tool items, and they manually add the `c:tools/knife` tag to their mod, I just think it's weird that neoforge does not have the native tag already. We already have 3 major mods adding knives to 1.21.x (Occultism, Aquaculture, Farmer's Delight). I think it would be very helpful to add that Tag to Neoforge base since I have seen some mistakes when modders try to manually add the tag to their items, as they keep switching between `c:tools/knife` and `c:tools/knives`

![image](https://github.com/user-attachments/assets/c8327061-0f69-43ba-bd96-c01650167995)

Just add to tools.json file in src/generated/resources/data/c/tags/item/
```
{
  "values": [
    "#c:tools/knife
    {
      "id": "#forge:tools",
      "required": false
    }
  ]
}
```

**Comment by TelepathicGrunt** [comment]
It’s better to ask the modders to follow the tag conventions. We got a lot of examples here to try and make it easier for people to know how to name their tag and where to put it. Anyone using c:tools/knives is wrong and needs a bug report to use c:tools/knife because one would say “Knife tools” and not “Knives tools”. Knife is the adjective describing the noun of tools

**Comment by sciwhiz12** [comment]
I agree with @TelepathicGrunt above: modders should follow the conventions of the common tags, whether by looking at documentation, asking around for how to add a tag, or following the pattern of the tag-to-be's siblings. 

Adding a tag _in NeoForge itself_ (and by extension, since we share common tags, in Fabric) for nebulous criteria such as "major mods add this" or "many mods add this" would be untenable, as that opens the door for many likely-frivolous requests to add this tool or that ingot or this fluid type to the common tags. 

The main benefit of common tags are the _pattern_ they lay out, which modders can extend to cover their own definitions and overlap with other mods adding the same definitions. What tags we provide matter only to add Minecraft's content to them, so modders can use them in substitute of hardcoding or using their own custom-tailored tags. (Even then, modders might make their own tag that takes values from common tags.)

In line with this, closing as not planned.

**Comment by TelepathicGrunt** [comment]
Well, we do add some common tags in foods that many mods have. But this feels more like a case we could add knives to the log warning to tell modders to go to knife. Not sure knife is fully worth having a dedicated modloader tag yet. Let’s try educating the knife mods first
