### ISSUE TITLE
Add a way to invert attribute color in tooltips

### ISSUE THREAD

**Issue by Lykrast** [neoforged/NeoForge#1502]
When an attribute modifier is displayed on a tooltip (like for armor values, melee attack damage/speed, and potions), it's hardcoded in vanilla that increase = blue (implied good) and decrease = red (implied bad).

Would be nice to have a way to switch that around for specific attributes when it's intended that decreasing it is good instead. And it sounds like a generically useful that would be messy if like 3 separate mods mixined their way to fix theirs.

My practical example where I'm having this issue is for a gun mod: I want attributes to change the gun behavior, and "spread", "fire delay", and "chance to consume ammo" are all attributes where lower is better.
I could take the reciprocal of "spread" and "fire delay" to force them in the way vanilla wants (though it will make tooltips less clear), but "chance to consume ammo" can't be cleanly converted like that (it should either display "+40% chance to not consume" or "-40% chance to consume", the latter lets me just use multiply total to make them stack multiplicatively (-40% on 2 armor pieces/potions should be -64%), the former I can't find a way that would work while displaying that number).

**Comment by sciwhiz12** [comment]
I believe this is already a feature in vanilla Minecraft: `Attribute.SENTIMENT` captures whether an attribute is 'positive' or 'negative' (or 'netural'). Where 'positive' attributes show blue for increases and red for decreases, 'negative' attributes show red for increases and blue for decreases. ('Neutral' attributes show gray for both increases and decreases.)

The default sentiment value is 'positive'. Some attributes like the fall damage multiplier attribute have a sentiment of 'negative' (since if the multiplier is increased, damage to the player increases, which is bad for the player). Some attributes like the entity scale attribute have a 'neutral' sentiment (since an increase or decrease of the attribute doesn't imply good or bad to the player).

Closing as already implemented in vanilla MC.

**Comment by Lykrast** [comment]
Ooh, wait when was this added?

*(As I did not have a 1.21 set up, before writing that issue, I asked for someone who had a 1.21 if the tooltip colors were still hardcoded like positive here and they told me yes, so they must have missed that.)*

**Comment by sciwhiz12** [comment]
Based on a look through of the source, `Attribute.Sentiment` was added in 24w19a, a snapshot of 1.21, which resolved [MC-268772](https://bugs.mojang.com/browse/MC-268772) ("Fall damage multiplier attribute has unintuitive coloring").

**Comment by Lykrast** [comment]
Alright thanks a lot!
