### ISSUE TITLE
Back-compat tags missing

### ISSUE THREAD

**Issue by PaintNinja** [neoforged/NeoForge#1594]
**Minecraft Version:** 1.20.6, 1.21.1

**NeoForge Version:** 20.6.121, 21.1.69

**Logs:** Attached is a dump of the loaded `forge` namespace tags found by [CommonTagsDumper](<https://github.com/PaintNinja/CommonTagsDumper>): [NeoForge 21.1.69 tags dump.md](https://github.com/user-attachments/files/17364573/NeoForge.21.1.69.tags.dump.md)

**Steps to Reproduce:**

Method A:
 1. Go to https://github.com/neoforged/NeoForge/tree/22971888941fcdef33b63f957657ad2a111c5925/src/generated/resources/data
 2. Observe that the forge tags folder is missing

Method B:
 1. Attempt to check against a legacy Forge tag, such as `forge:cobblestone`
 2. Observe that it never evaluates to true when checking against a cobblestone itemstack 
```java
var cobble = new ItemStack(Items.COBBLESTONE);
var forgeCobbleTag = ItemTags.create(ResourceLocation.fromNamespaceAndPath("forge", "cobblestone"));
boolean isCobble = cobble.is(forgeCobbleTag);
```

**Description of issue:**
PR https://github.com/neoforged/NeoForge/pull/135#:~:text=Backwards%20compat%20with,update%20their%20tags and its source code seem to indicate an intention to maintain backwards compatibility with content that uses the old tag names until 1.22.

While there are indeed optional entries added for these old tags, the tag contents are empty because they are not defined anymore. This means that content which checks against the old tags no longer works as expected.

Related: https://github.com/MinecraftForge/MinecraftForge/pull/10126

**Comment by TelepathicGrunt** [comment]
Not a bug. 

We deliberately chose to merge the unify work during a large breaking Mc version due neo beta without keeping the old tags. This is intended. We added weak backwards compat  in the form of new tags optionally reading from old tags but ultimately, the log warning pushes devs to move off the old unsupported tags to the new tags.

And it worked well and modders have been making the switch without issue. We do not see any benefit to re-adding the old tags. In fact, it would be more detrimental to add the old tags back as that weakens the incentive to migrate to new tags as well as causes confusion to the old tag modder as the old tag will not have the modded entries that other devs are adding to the new tags

**Comment by PaintNinja** [comment]
You may wish to update the PR description to distinguish between using old tags and adding to old tags, as it currently states that existing jars and datapacks that use the old tags will continue to work:

> This will allow built jars and datapacks using the old tag names to continue to have compatibility throughout 1.21 Minecraft. Then these backwards compatibility can be deleted in 1.22 Minecraft to clean up this remaining tech debt as everyone had an entire major Minecraft version to update their tags.

**Comment by TelepathicGrunt** [comment]
Old mods and datapacks that tag things under old tags will work with new system as new tags pulls them in. That’s what I mean. It works in that direction. The other direction is what is unsupported to incentivize people to the new system as otherwise, no one will move. 

(Edit: to be clear, this was thought about very heavily. It’s one way compat so that taggers still work with readers. It’s readers still using old tags that won’t get all entries anymore to force them to read new tags. And the old taggers get the log warnings to migrate. If we kept the old tag, the old readers will never know to migrate because we have no way of ever detecting them and warning them.)

Changing the old pr description isn’t gonna help anyone as there has been so many more adjustments and changes since then. Even the pr description itself is a mess of strikethrough and edits due to it constantly changing back then. No one is reading that pr description anymore

People should be looking at the current tag javadocs and files. Or the console with the log warning telling them how to migrate their tags. Or the neo blog post and/or docs: https://neoforged.net/news/20.5release/#tag-convention-updates
https://docs.neoforged.net/docs/resources/server/tags
