### ISSUE TITLE
Minecraft Demo overlay is not rendered with NeoForge

### ISSUE THREAD

**Issue by Lolothepro** [neoforged/NeoForge#166]
Vanilla:
![2023-10-04_18 38 06](https://github.com/neoforged/NeoForge/assets/68275908/ac729f24-d149-47bb-90f1-832cc3e61317)

Neo:
![2023-10-04_18 36 31](https://github.com/neoforged/NeoForge/assets/68275908/a259f261-8a27-4206-8e17-716cf4c3959e)

(time remaining in left/right corner)

**Comment by KnightMiner** [comment]
Is this a bug though? The vanilla one looks barely readable due to the overlap, so looks like a Forge fix. I assume when the debug screen is disabled the two look the same.

**Comment by Lolothepro** [comment]
No, even when the F3 menu isn't open, the two are rendered differently. With NeoForge, it's rendered as an always visible part of the F3 menu (even when the F3 menu isn't opened).

**Comment by Lolothepro** [comment]
Neo:
![2023-10-05_17 59 03](https://github.com/neoforged/NeoForge/assets/68275908/c5916ec8-fad1-41c1-ab97-5a3a18f9f1bc)

Vanilla:
![2023-10-05_18 00 32](https://github.com/neoforged/NeoForge/assets/68275908/19c1ea50-bb89-4126-9aab-6966d0c1f7d0)

**Comment by Shadows-of-Fire** [comment]
Is this even an issue we should care about? Using Neo is conditional on owning the game; using Neo and the demo is an unsupported mix.

**Comment by TelepathicGrunt** [comment]
@sciwhiz12 Are you sure bug label even applies here? The neo version is better and honestly preferred imo. Makes me wonder if this was intentionally done in the first place

**Comment by sciwhiz12** [comment]
On its face, this looks to be a change of behavior inconsistent with vanilla and doesn't seem to be intended, which is generally the criteria I use when labelling issues with https://github.com/neoforged/NeoForge/labels/bug. (The https://github.com/neoforged/NeoForge/labels/triage label is there to signal that the issue hasn't been triaged yet, i.e. considered at length if it's an actual bug or a bug worth fixing; I generally add labels first and triage later.)

Once someone (like me, or any other maintainer) makes the judgement call that this is a bug and it is worth fixing, i.e. triaging it, they can then remove the https://github.com/neoforged/NeoForge/labels/triage label and move it to the appropriate status in the Triage board.

On this matter, I'd like to check if this is intentional, and if we can make it so it renders in the vanilla-esque manner when the debug menu is disabled (with the current behavior left intact when the debug menu is visible).

**Comment by Lolothepro** [comment]
Since Minecraft 1.20.2, it's no longer rendered, which makes me think it's a bug.
so it's probably not intentional

**Comment by Lolothepro** [comment]
NeoForge:
![2023-12-10_11 18 22](https://github.com/neoforged/NeoForge/assets/68275908/104c6db0-65c6-48a6-bc2b-1287e7424f76)

Vanilla:
![2023-12-10_12 19 33](https://github.com/neoforged/NeoForge/assets/68275908/601fb7aa-e561-4195-8bae-8ee27c6fa105)

**Comment by TelepathicGrunt** [comment]
Issue is the demo overlay is not in VanillaGuiOverlay class
