### ISSUE TITLE
Standard Vanilla behaviour changed on piston changing a block on which a sign is placed

### ISSUE THREAD

**Issue by bitberlin** [neoforged/NeoForge#1699]
**Minecraft Version:** 1.21.1

**NeoForge Version:** 21.1.80

**Logs:** -

**Steps to Reproduce:**
 1. Place a moss block
 2. Place a stone block next to the moss block
 3. Place a piston next to the stone block pushing in direction to the stone block (and the moss block)
 4. Place a sign on the side of the moss block (so that it will after piston action be beside the stone block)
 5. Let the piston push (with a lever or button next to it)
 6. The sign breaks and falls off

The issue here is that the sign stays in place in Vanilla Minecraft, in Neoforge it breaks.

The issue occurs with no mods installed.

EDIT:
Here some screenshots to understand it.
NeoForge 21.1.80:
![Image](https://github.com/user-attachments/assets/d3353498-78af-4ad0-9098-569cdfed7b05)
![Image](https://github.com/user-attachments/assets/40e702bd-c1b6-4d6d-af0f-5fd04060842b)

Vanilla:
![Image](https://github.com/user-attachments/assets/216e6ad8-30a3-4c72-ae2e-e8e389b28864)
![Image](https://github.com/user-attachments/assets/0e77c024-04c8-448c-acd6-fcc674f88dac)

**Comment by sciwhiz12** [comment]
Confirmed on 21.4.12-beta. Debugging reveals this to be caused by an outdated code, which is trivially fixable.

The `Block` & `BlockState` extensions has the method [`onDestroyedByPushReaction`](https://github.com/neoforged/NeoForge/blob/ac0abaf4745e00a475f3f4bb7b1ece84a4569b87/src/main/java/net/neoforged/neoforge/common/extensions/IBlockExtension.java#L236-L254), which is called when that block is destroyed by a piston. That method is called from [`PistonBaseBlock`](https://github.com/neoforged/NeoForge/blob/ac0abaf4745e00a475f3f4bb7b1ece84a4569b87/patches/net/minecraft/world/level/block/piston/PistonBaseBlock.java.patch#L31-L33), and the original code handling the block destruction is moved to the extension method.

However, as can be seen in the two links, the code originally in `PistonBaseBlock` slightly differs from the code in `onDestroyedByPushReaction`: the flag used in the call to `Level#setBlock` is a constant in the original `PistonBaseBlock` code, but the code in `onDestroyedByPushReaction` uses different flags (depending too on the logical side).

Synchronizing the code in `onDestroyedByPushReaction` to match the original code from `PistonBaseBlock` fixes the issue, with the sign attached to the moss block remaining unbroken when the moss block is destroyed (then replaced with the stone block).
