### ISSUE TITLE
[1.21.4]If you enter the Pale garden in 1.21.4. not music fade out

### ISSUE THREAD

**Issue by baguchi** [neoforged/NeoForge#1733]
**Minecraft Version:** 1.21.4
**NeoForge Version:** 21.4.2-beta

**Description of issue:**

The background music that should fade out in Pale Garden doesn't fade out.

mayby ```net.minecraft.client.Minecraft#getSituationalMusic``` is not support fade out?

**Comment by sciwhiz12** [comment]
As noted in https://github.com/neoforged/NeoForge/pull/1766#issuecomment-2559770847, the issue is due to `BiomeSpecialEffectsBuilder` failing to copy over the `backgroundMusicVolume` field from the original info (which is `0.0F` for the pale garden biome), thus causing the modified info to hold the default value of `1.0F`. The fix is as simple as modifying the builder to copy that field.
