### ISSUE TITLE
Minecraft version in installation version

### ISSUE THREAD

**Issue by joveaaron** [neoforged/NeoForge#1790]
Instead of neoforge-21.3.58 make it say neoforge-1.21.3-21.3.58
might be long but when the profile name is the same and you have multiple versions installed you _will_ forget what minecraft version it is, which is much more important than the neoforge version. please consider this.

also, one thing to note that is completely unrelated: the animation at the bottom right when loading into the game uses the fox instead of the anvil. the anvil was custom made and didn't use any copyrighted assets. the fox model and textures are a property of Mojang/Microsoft. you might consider making your own animation to avoid legal issue. this is just a tiny tip

**Comment by Technici4n** [comment]
The 21.3 in the NeoForge version already tells you the MC version.

**Comment by sciwhiz12** [comment]
Per above, the NeoForge version deliberately includes the last two numbers of the Minecraft version. The first number is not included because Minecraft has not deviated from the `1.##.#` numbering scheme for a decade and more since its initial release. (We'll cross the bridge of `2.##.#` when we come across it.)

The one exception is for NeoForge versions released for Minecraft 1.20.1, which mimic the Forge versioning scheme at the time. NeoForge changed from that scheme to the current scheme in 1.20.2.

As for the fox animation, I believe the concern about that is minimal, but we'll take your suggestion under advisement in any case.
