### ISSUE TITLE
make base game behavior patches optional

### ISSUE THREAD

**Issue by TheBearodactyl** [neoforged/NeoForge#1795]
e.g. if someone wants string duping back they should be able to disable the tripwire patch

**Comment by AterAnimAvis** [comment]
I'll sum this up, no, we're not removing patches aimed at improving mod support because you want to dupe string.

In addition in 1.21.2+ this isn't even relevant anymore since Mojang have fixed the underlying issue themselves [MC-129055](https://bugs.mojang.com/browse/MC-129055)

Whilst Neo does try and aim for Vanilla parity, our main focus is on Mod compat / support, the dupe "fix" was a side effect of us patching tripwire so it doesn't break modded shears. adding toggles for all 700+ patch files we have (that's not individual features but actual files) isn't feasible or in any way likely.

**Comment by TheBearodactyl** [comment]
rip
