### ISSUE TITLE
1.7.10 support?

### ISSUE THREAD

**Issue by johnch18** [neoforged/NeoForge#2]
Look, I know you have your position on this, but 1.7.10 is still actively modded far more than many recent versions, and there are things that could be improved. Just sayin'.

**Comment by KiriCattus** [comment]
![IMG_4744](https://github.com/neoforged/NeoForge/assets/19393068/b9d7c417-aefe-4894-a497-630e3b044de1)
Stats pulled from CurseForge would beg to differ greatly as well as the community as a whole 😂 that and personal experience watching large modding communities talk about/helping each other mod for recent versions is still very much alive in 1.16, 1.18, 1.19 and 1.20. We get the odd few visitors asking for modders to mod with 1.12 and modders that still work there too

**Comment by johnch18** [comment]
The key word in what I said is "actively"

**Comment by jss2a98aj** [comment]
> Stats pulled from CurseForge would beg to differ greatly as well as the community as a whole

CurseForge lacks most old and many new 1.7.10 mods. Modern versions also have massive quantities of mods that add very little content in order to maximize curse points. The 1.7.10 community is also quite active looking at GTNH and Legacy Modding.

That said, just having 1.7.10 Forge (Neo branded or not) building and open to PRs would be quite substantial.

**Comment by LeStegii** [comment]
1.7.10, 1.12.2 and possibly other versions still have quite an active and often techy community, with many optimization mods and so on. I might be blue-eyed here, but having community driven development with official releases would be great.
However, even if that wouldn't be possible or out of scope, maybe it'd be possible to at least allow talking/asking about these older versions in forums and such without being warned.

**Comment by Desoroxxx** [comment]
I will state in this issue what I have stated on Discord as GitHub issues tend to not get lost like Discord messages.

I know it is a ton of work to just keep a version "alive" but if you are open to having someone to deal with that for 1.12, I am here, there are also other devs that would be happy to work on just maintaining 1.12 and 1.7.

As for toolchain, at least on the mod dev side we already have RetroFuturaGradle for 1.7 and 1.12 which is amazing and provides a seamless modding experience.

It is still incredibly early to have this discussion though. Although I am fully available for any kind of activities, I understand that all of the team must be super busy with recent events.

**Comment by quat1024** [comment]
The main problem with updating the main loader is that if any change breaks a mod, like, that mod is not coming back. Most Forge 1.7 mods are abandonware and that's perfectly fine, it just means the project needs to be very careful about what it adds and changes, [even if it fixes an "obvious bug"](https://lwn.net/Articles/779997/). Maintaining the existing set of mods is much more important than adding superficialities. And honestly a lot of the late-blooming Forge 1.7 mods were probably developed under the assumption that Forge itself was abandonware, given the vitriolic official stance towards 1.7 for the past 400 centuries. Hyrum's law abounds.

The GTNH project does incredible things with Forge 1.7, but they do it with the benefit of being able to hammer a mod into shape if their changes break it. This is perfectly fine for GTNH's goals, but it is not a good position for the *central* loader project at the heart of it all to take. No recklessness, no move-fast break-things.

Also Yes keep in mind that just because there is no magic forcefield repelling anyone that speaks the name of 1.7 it doesn't mean the capacity of the lead developers has suddenly tripled :shipit: 

That said, it'd be nice to see some of the bitrot taken care of. Afaik a lot of work on tooling bitrot has already been taking place w/ retrogradle and the like, but it's slow and hard work that hasn't reached specifically 1.7 yet, and i think the popularity of stuff like gtnh gradle shows that a buncha people are thinking "fg5 for 1.7 would be nice but can someone just duct-tape fg2 into shape in the meantime"

Apart from addressing bitrot & not stifling the community, im not really sure what forge1.7 really needs tho? Forge 1.7 is a very complete product already

**Comment by SAGESSE-CN** [comment]
> ![IMG_4744](https://user-images.githubusercontent.com/19393068/253162172-b9d7c417-aefe-4894-a497-630e3b044de1.jpeg)

I think fabric and similar designs lead to a lot of invalid lib mods, so the data 1.16+ is distorted.

I would say that 1.7-1.15 and 1.16+ are not directly comparable.

**Comment by johnch18** [comment]
I guess what I'd ideally like to see is some of the MC version agnostic features, improvements, or bug fixes being tossed back our way. I wouldn't much like the API to break, but offering newer features and improving core performance would be very useful

**Comment by johnch18** [comment]
At the end of the day, 1.7.10 still has a lot of people passionate about it and trying to tinker with it. And yes, I'd agree most of us are under the impression we'd be using *.1614 for the rest of eternity, but that doesn't mean we wouldn't like to go beyond that if possible

**Comment by Desoroxxx** [comment]
> 

Changes are not equal braking change, you can very well change things and fix issues etc... without breaking mods

**Comment by DaemonUmbra** [comment]
> ... but 1.7.10 is still actively modded far more than many recent versions ...

This claim is backed only by rhetoric as far as I am aware.
Primary support will always be for the most recent versions, if you really want to see support for 1.7.10 you are free to join the [RetroGradle](https://github.com/RetroGradle) effort.

**Comment by SizableShrimp** [comment]
While we do need to consider what our policy for legacy versions will be going forward, that is not something we can settle until we get our feet in the ground first with just a single version, 1.20.x. This conversation doesn't seem to be super productive right now, so I will lock it and we can possibly unlock it or start a new discussion at a later date. Thanks.
