### ISSUE TITLE
The "Elevators" datapack by Vanilla Tweaks is broken with NeoForge

### ISSUE THREAD

**Issue by Lolothepro** [neoforged/NeoForge#230]
**Minecraft Version:** 1.20.2

**NeoForge Version:** 20.2.20-beta

NeoForge:

https://github.com/neoforged/NeoForge/assets/68275908/865913a8-6c15-41da-a922-3f73ebc4a14d

Vanilla:

https://github.com/neoforged/NeoForge/assets/68275908/51761ff6-9b4b-45ec-aa76-b525d4eb5839

The datapack is supposed to turn wool into an elevator when an Ender pearl is dropped on it.

https://vanillatweaks.net/picker/datapacks/

**Comment by XFactHD** [comment]
I've dug into this and found that this is caused by a `LootItemCondition` failing to load due to an issue with the conditional codec. For some reason, the conditional codec tries to read a property with the key `value` from the incoming JSON and fails because there is no such property.

The error printed in the log is `[23:03:01] [Worker-Main-26/ERROR] [minecraft/LootDataType]: Couldn't parse element predicates:elevators:loaded - Not a json array: null`.
This is a stacktrace captured at the specific point where the error is thrown: https://gist.github.com/XFactHD/dd7c67db28ef4d370eb68ecccd0ba4a4.
The JSON file it's erroring on is located at `data/elevators/predicates/loaded.json` in the elevator datapack (can be found under the Experimental category on the page linked by the OP).
The error originates from this patch: https://github.com/neoforged/NeoForge/blob/1.20.x/patches/net/minecraft/world/level/storage/loot/LootDataType.java.patch#L44-L58 and happens due to this call with the `value` key: https://github.com/neoforged/NeoForge/blob/1.20.x/src/main/java/net/neoforged/neoforge/common/conditions/ConditionalOps.java#L142

I'm having a hard time sifting through the whole codec callstack, so I would appreciate any feedback from those originally involved in implementing the conditional codec.

**Comment by marchermans** [comment]
I wrote that section, we tested the codec system on a lot of things, weird that this does not work.

I will check it out tomorrow
