### ISSUE TITLE
The player's attack range is increased with NeoForge

### ISSUE THREAD

**Issue by Lolothepro** [neoforged/NeoForge#243]
**Minecraft Version:** 1.20.2

**NeoForge Version:** NeoForge-20.2.26-beta

NeoForge:

https://github.com/neoforged/NeoForge/assets/68275908/cb7a0e27-c563-4700-8085-fd9837c334f0

Vanilla:

https://github.com/neoforged/NeoForge/assets/68275908/73fbcddf-efa7-4664-b7e3-a8f2f2ca1365

World:
[Reach.zip](https://github.com/neoforged/NeoForge/files/13254081/Reach.zip)

**Comment by LoganDark** [comment]
I think this could be because creative mode has slightly increased block reach and maybe someone tried to unify reach for blocks and entities

**Comment by Shadows-of-Fire** [comment]
I guess someone fucked this patch in porting again, as has happened every time since it was introduced, lol

**Comment by pupnewfster** [comment]
If it is the same specific part of the patch as got messed up last time, we should probably add a comment as part of the patch that tries to clarify what should be used there.

**Comment by Shadows-of-Fire** [comment]
I don't think its the same part of the patch, the previous part was due to vanilla adding new cap constants that meant our changes were getting capped - this looks like something is being offset by a value incorrectly.

**Comment by Shadows-of-Fire** [comment]
So this is just a resurfacing of a vanilla bug: https://bugs.mojang.com/browse/MC-250858

Vanilla declares an entity reach distance of 6.0 for creative players in `GameRenderer#pick`, but then forgets a `!= MISS` check and truncates it to `5.0` (the block reach) inadvertently.

This only impacts creative players, but we have to add the miss check to support disjoint ranges (otherwise all ranges are truncated to the block range).

We can probably reduce the creative entity reach boost from 3 to 2 to compensate for vanilla's issue.
