### ISSUE TITLE
Dead bushes can be placed on glazed terracotta, unlike vanilla.

### ISSUE THREAD

**Issue by Lolothepro** [neoforged/NeoForge#306]
https://github.com/MinecraftForge/MinecraftForge/issues/8732

**Comment by Lolothepro** [comment]
Note: https://github.com/MinecraftForge/MinecraftForge/issues/9493

**Comment by sciwhiz12** [comment]
Looking through the code shows the cause to be simple: in the [`Block` patch which implements `PlantType`](https://github.com/neoforged/NeoForge/blob/aa32f544ec23743124814ee491ca9573a7a8339e/patches/net/minecraft/world/level/block/Block.java.patch#L152-L153), the `DESERT` plant type is allowed to be placed on glazed terracotta. 

That is in error, since there is no vanilla plant which is placeable on glazed terracora, and there is no reason that plants should be placeable on glazed terracotta.

After a bit of patch hunting throughout the ages, I believe I've narrowed down the source of that particular error. In https://github.com/MinecraftForge/MinecraftForge/commit/7c0d94ce9c7481fe4a122aa5731aa3becbaf317f#diff-67749f72fc217feef6791d7e82996c56ab23ef92ce892c85560585198543f040R233, one of the patches of the 1.13 porting efforts, it seems the `EnumPlantType`[^1] patch was reimplemented with that addition of the check against the glazed terracotta class. (Previous versions of the patch did not use glazed terracota.)

While I think the best long-term course of action here is to revisit the `PlantType` system -- to either improve it or replace it -- the short-term solution is to simply remove glazed terracotta from the `DESERT` plant type check. It will be a minor regression, as desert plants will not be placeable on glazed terracotta, but I think it's minor enough that no mod will substantially notice.

[^1]: The `Enum` prefix is a relic of that era, which was borne out of (as I recall from past conversations) the need to specifically identify `enum`s during the time when all Minecraft classes were placed under the `net/minecraft/src` package, when subpackages were not yet used in the mappings.
