### ISSUE TITLE
Uncontrolled list type for mob effect curative items

### ISSUE THREAD

**Issue by kirderf1** [neoforged/NeoForge#322]
**Minecraft Version:** 1.20.2

**NeoForge Version:** 20.2.86

**Steps to Reproduce:**
 1a. Make a custom mob effect that overrides `getCurativeItems()` and returns an unmodifiable list, and create a mob effect instance from it. OR:
 1b. Obtain any mob effect instance and call `mobEffectInstance.setCurativeItems(List<ItemStack>)` with an unmodifiable list.
 2. On the same mob effect instance, use `mobEffectInstance.addCurativeItem(ItemStack)` with a different item.

**Description of issue:**
Following the steps above, an `UnsupportedOperationException` should be thrown. The problem with this is that `addCurativeItem()` assumes that the list is mutable, and it is easy for a mod that overrides the curative item list to accidentally use an immutable list.

**Solution discussion:**
The simplest solution would be to change how the item list in the instance is handled, initializing it as a mutable copy of the list returned from `mobEffect.getCurativeItems()`, and in `mobEffectInstance.setCurativeItems(List<ItemStack>)`. There's also an opportunity to reshape this api in a different way, such as by changing `mobEffect.getCurativeItems()` from returning a list to modifying a list argument.

Note: This is not a problem I have experienced myself, but rather one that I identified from the perspective of overriding `mobEffect.getCurativeItems()`.

**Comment by KnightMiner** [comment]
To be honest, the current implementation of curative items is just way more messy than it should be. The list of item stacks makes it a pain to create items that cure like milk, and is rather limited in flexibility for curing custom effects.

I'd recommend just ditching the item stacks entirely in favor of a system like tool actions, call it something like "effect cures". Mob effects can have an internal mutable set of effect cures, and effects could override the method that fills the set (rather than returning the set).
