### ISSUE TITLE
Mod annotation scanner slows down launch

### ISSUE THREAD

**Issue by embeddedt** [neoforged/NeoForge#33]
The Forge mod annotation scanner is rather slow and can take over 20 seconds to scan mods in a large enough modpack. A simple optimization that could improve this is to provide the flags that skip parsing code, debug info, and frames [on this line](https://github.com/MinecraftForge/MinecraftForge/blob/30f255d76c4c2e915414a24e6d8aed42f429817e/fmlloader/src/main/java/net/minecraftforge/fml/loading/moddiscovery/Scanner.java#L48).

```diff
-        cr.accept(mcv, 0);
+        cr.accept(mcv, ClassReader.SKIP_CODE | ClassReader.SKIP_DEBUG | ClassReader.SKIP_FRAMES);
```
I've tested this change in modpacks using [an external agent](https://github.com/embeddedt/Blacksmith/blob/d5f3f46e785cca5a3dc0719668589e6ce6fe74c8/src/main/java/org/embeddedt/blacksmith/impl/transformers/FMLScannerTransformer.java#L28), and it seems to give a free performance boost to the scanner without requiring any invasive changes. However, in the long term, it would also be prudent to consider caching this data rather than rescanning mods on each startup, as this is a waste of time. A cache might also allow retrieving the data from disk as needed instead of needing to permanently store many `ModFileScanData` objects, which wastes memory especially since many of the annotations might never be queried.

**Comment by PaintNinja** [comment]
I looked into this recently but didn't get around to testing it as I was struggling setting up a proper profiler to actually get some numbers on this and people were being unhelpfully vague.

While this theoretically would speed things up for finding `@Mod`, depending on how other Forge internals work it might break EventBusSubscriber and the like, due to needing to read parameters which this turns off. If true, that would explain why it's a lot faster to load for you as it would be skipping a lot of event listeners.

We need actual numbers on this and testing with EBS and OnlyIn to know the exact performance difference this has and that it doesn't break other stuff in the process. A couple of JFR dumps or similar will do

**Comment by embeddedt** [comment]
> it might break EventBusSubscriber and the like, due to needing to read parameters which this turns off. 

Are you sure about this? A quick cursory glance at `ClassReader` suggests `SKIP_CODE` applies specifically to the bodies of methods - from what I can tell annotation parsing wouldn't be affected.

**Comment by PaintNinja** [comment]
You’re suggesting `ClassReader.SKIP_CODE | ClassReader.SKIP_DEBUG | ClassReader.SKIP_FRAMES`

And no I'm not sure, I'm saying it's something that needs to be aware of and tested. Speeding up mod loading is great but it's not that great if half of them don't actually load anymore...

**Comment by Tslat** [comment]
Have we considered moving to a SL-style declaration like fabric/quilt does? Declare the entrypoint paths in the mods.toml and remove the mod annotation entirely?

This also has the added benefit of allowing for multiple entrypoints per mod, which I've seen used in some fabric/quilt mods to beneficial effect

**Comment by SizableShrimp** [comment]
This is a possibility.
However, before that even matters, to properly move away from scanning the entire mod jar on load, we must get rid of the following Forge-used annotations:
- `@Mod`
- `@EventBusSubscriber`
- `@GameTestHolder`
- `@ObjectHolder`
- `@AutoRegisterCapability`

Not to mention the fact that mods may also use this data aswell.

**Comment by TheCurle** [comment]
I don't believe anyone is suggesting we remove scanning entirely.

For now, there are two easy paths forward:

- don't scan *method body bytecode*
- cache the scan results (per jar hash?) on first launch with a new mod jar rather than rescanning every launch

Both of these are relatively simple to implement, don't involve removing the entire system, and should remain compatible with all existing mods, yet should provide reasonable performance boosts for the work being done.

**Comment by Tslat** [comment]
Totally forgot that the CR would be scanning for the other annotations lol

Caching the scan results here would very likely be the best bet

**Comment by Tslat** [comment]
Summary of discussion in Discord:

- Look at implementing compile-time scanner for runtime retention annotations
  - Capture all annotations, compile into service-loader style data package in meta-inf
  - At runtime, skip full class-reader sweep entirely unless a mod is missing that datapackage
    - If not missing, use service locations in package to identify classes to be scanned directly
    - If missing, fall back to full sweep like current system
- Optionals:
  - Add lookup functionality in a NeoForge class somewhere for direct usage by other mods without needing SPI or service-loaders
  - Add fallback 'marker' that can be set in mods.toml or similar to tell NeoForge to just do a full sweep anyway

@TheCurle 
@Matyrobbrt 


Link to "read down from here":
https://discord.com/channels/313125603924639766/852298000042164244/1130974684461154304

**Comment by Technici4n** [comment]
Closing as fixed now that we are running it in parallel.
