### ISSUE TITLE
Consider disabling syncWrites/setSyncChunkWrites by default

### ISSUE THREAD

**Issue by Speiger** [neoforged/NeoForge#356]
Mojang decided on enabling synced chunk writes by default.    
Which technically reduces the risk of Safe File corruption due to the nature of how chunkloading now works.   

And while that is/sounds like a good idea, it sadly is not really all that good.
It basically amplifies the usage on HDDS drastically.
Maxing out HDDs on a simple pregen task for example while when synced writes are disabled it runs at a cool 10-15% max (assuming you can generate hundreds of chunks per second) on a 5400RPM HDD.

In general, sync chunk writes are simply not helping as much as mojang believes compared to the strain on the actual hardware.

Note, it is just a suggestion from what i have experienced.

**Comment by Speiger** [comment]
Here is a example showing the difference between Synced Chunk Writes Enabled/Disabled when using the neoforge pregenerator.

Which is way less aggressive in saving its data.

<details>
<summary>Sync Chunk Writes enabled</summary>
<p>

![Synced Chunk Writes Enabled](https://github.com/neoforged/NeoForge/assets/2556269/8dc53014-65c5-462f-9d97-3e4b93c2dd3b)

</p>
</details>

<details>
<summary>Sync Chunk Writes disabled</summary>
<p>

![Synced Chunk Writes Disabled](https://github.com/neoforged/NeoForge/assets/2556269/fe8d101a-6558-4c86-af2b-bdfb94bf4b2c)

</p>
</details>

And here the difference is already pretty big.
Not as bad as I had it in other cases but still.

**Comment by TelepathicGrunt** [comment]
> Which technically reduces the risk of Safe File corruption due to the nature of how chunkloading now works

_Copying my response from discord:_ 
I think prioritizing not leaving the world in a corrupted state is more important than a small bit of performance.
Less performance is manageable. Broken and unfixable world is unacceptable.

**Comment by Speiger** [comment]
@TelepathicGrunt i argue against this with the following reason:
- Minecrafts FileManagement is 100% singlethreaded, and it is made out of pure singletons. All Reads/writes go through the same RandomAccessFile instance and there is only 1 thread accessing that at the same time, yes it has dedicated access threads but it is singlethreaded in nature. So a snyc makes no sense.
- Older Versions do have no file sync flag set and on top of that never have had corruption issues had due to the file system not writing data properly. Corruption usually happend due to running out of ram or running full on disk, or crashing at the middle of the saving, which usually was linked to running out of ram or having an infinite iterator. Synced writes never protect against that.
- The "unproven corruption protection increase" comes at a big cost of unnecessary hardware strain. We talk about a 2000% increase in disk usage just from generating a few chunks a second.

The documentation from [Java](https://docs.oracle.com/javase%2F7%2Fdocs%2Fapi%2F%2F/index.html?java/nio/file/package-summary.html) also states:
> Synchronized I/O File Integrity
The [SYNC](https://docs.oracle.com/javase%2F7%2Fdocs%2Fapi%2F%2F/java/nio/file/StandardOpenOption.html#SYNC) and [DSYNC](https://docs.oracle.com/javase%2F7%2Fdocs%2Fapi%2F%2F/java/nio/file/StandardOpenOption.html#DSYNC) options are used when opening a file to require that updates to the file are written synchronously to the underlying storage device. In the case of the default provider, and the file resides on a local storage device, and the [seekable](https://docs.oracle.com/javase%2F7%2Fdocs%2Fapi%2F%2F/java/nio/channels/SeekableByteChannel.html) channel is connected to a file that was opened with one of these options, then an invocation of the [write](https://docs.oracle.com/javase%2F7%2Fdocs%2Fapi%2F%2F/java/nio/channels/WritableByteChannel.html#write(java.nio.ByteBuffer)) method is only guaranteed to return when all changes made to the file by that invocation have been written to the device. These options are useful for ensuring that critical information is not lost in the event of a system crash. If the file does not reside on a local device then no such guarantee is made. Whether this guarantee is possible with other [provider](https://docs.oracle.com/javase%2F7%2Fdocs%2Fapi%2F%2F/java/nio/file/spi/FileSystemProvider.html) implementations is provider specific.

The summary of that is:
- It protects that the file system writes complete on system level crashes. (I assume JVM/Operating system crashes here)
- It doesn't protect on power failure. Since its basing its insurance on the "provider implementation"

Overall again this is my opinion.
If you disagree that is fine. But i wanted to make a proper case at least.

**Comment by Niko-sk2x** [comment]
I said it on discord before so I'm also going to write it here: it is possible to implement it significantly more efficiently by writing multiple chunks at once and using `force()` method instead of `DSYNC` flag (I implemented it and this is quite a significant improvement). Whether it is something that would be implemented in neoforge, I don't really know. Going by the example of Forge implementing async chunk loading in the past (1.12.2 and older), it doesn't look completely unreasonable to me.

> Older Versions do have no file sync flag set and on top of that never have had corruption issues had due to the file system not writing data properly. Corruption usually happend due to running out of ram or running full on disk, or crashing at the middle of the saving, which usually was linked to running out of ram or having an infinite iterator. Synced writes never protect against that.

Sync writes do protect the save in all of the above cases. In general, it protects against pretty much everything except power failure - Minecraft more or less implements [shadow paging](https://en.wikipedia.org/wiki/Shadow_paging) on region files here (whether it also ptotects against power failure is very likely to depend on the underlying hardware, in my real world tests on my hardware it appeared to protect the save even in case of power failure). And modded environment is especially prone to crashes that could interrupt saving chunks (which I have seen happen before in older versions, and I have lost modded worlds before due to corrupted chunks after crashes).

It is a bit strange to me that on the client, Minecraft enables it only on Windows, I don't really know why.

**Comment by TelepathicGrunt** [comment]
Closing this as due to being a modloader that will be widely used by players, we rather focus on data safety/integrity. It's not something we would give up for performance. However, a mod can disable these methods themselves and that is ok. At the very least, players would have the option to opt-in to doing this tradeoff for performance and keeps the modloader itself out of the blame for when things do go wrong.
