### ISSUE TITLE
What has happened to Forge?

### ISSUE THREAD

**Issue by jdz-green** [neoforged/NeoForge#36]
Sorry to bother you. I'm a player of Minecraft from China. Early today,I noticed that Forge was rebranded to NeoForge.Why was Forge rebranded?I use Forge to play mods on Minecraft every day, so I'm wondering if this is going to make any difference to the game.If possible, could you please tell me what has happened to Forge? I am looking forward to your reply.Thanks!

Here is the news about Forge in China player groups.

**Comment by jdz-green** [comment]
https://github.com/huanghongxun/HMCL/issues/2406

**Comment by Napoleon-x** [comment]
So the owner of forge said some mean words to college liberals of the forge team so they staged a hostile takeover? That is rather funny

**Comment by marchermans** [comment]
@Napoleon-x Trolls are not welcome here.

@jdz-green Only the discord server was rebranded. The Forge project website and github repositories remain Forge. Forge has a new discord server you can join if that's what you want to do.

**Comment by sciwhiz12** [comment]
Just to clarify: Minecraft Forge still exists and is under the sole ownership of LexManos, who owns the company that owns the Minecraft Forge branding and other materials. 

Because of that, we were essentially required to pick a new name and brand for our fork of Minecraft Forge; hence, the name NeoForged (for the organization) and NeoForge (for the actual modding framework).

Our plan is to keep compatibility as much as reasonably possible with Minecraft Forge within 1.20.1, so mods which worked on Forge (around 47.1.3) also work on NeoForge. However, we will be diverging from Forge in cases where upstream changes do not fit (in a technical or design sense) for 1.20.1, and likely fully diverging when 1.20.2/1.21 arrives.

---

As for the reasons regarding the existence of NeoForged as a fork of Forge, I direct people to read [the blog post written by cpw](https://neoforged.net/news/theproject/), one of the founding members of NeoForge and a current permanent member of its steering council. 

In short, the leadership of Forge, LexManos, has been problematic in their behavior and actions for a long time, and a breaking point was reached in part because of the troubling treatment of senior contributors, leaders, and members of the team, and in part due to the toxic environment nurtured over many years by aforesaid leadership.

Rest assured, _many_ opportunities were taken in the past to try change and reform the environment and the leadership. However, despite all those actions proposed and implemented, and because of the ulterior motives which ultimately tainted some of those actions, little to no reform actually stuck to the wall, so to speak. A breaking point was then reached, and it was decided that reforming or defending the existing leadership was no longer viable; hence, the fork of NeoForged, with new leadership and new branding.

**Comment by jdz-green** [comment]
Thanks! Now I have learned that NeoForge is a new project but its team members are from Forge.We can use NeoForge to play Forge mods too.&nbsp;



---Original---
From: ***@***.***&gt;
Date: Thu, Jul 20, 2023 21:40 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [neoforged/NeoForge] What has happened to Forge? (Issue #36)




 
Just to clarify: Minecraft Forge still exists and is under the sole ownership of LexManos, who owns the company that owns the Minecraft Forge branding and other materials.
 
Because of that, we were essentially required to pick a new name and brand for our fork of Minecraft Forge; hence, the name NeoForged (for the organization) and NeoForge (for the actual modding framework).
 
Our plan is to keep compatibility as much as reasonably possible with Minecraft Forge within 1.20.1, so mods which worked on Forge (around 47.1.3) also work on NeoForge. However, we will be diverging from Forge in cases where upstream changes do not fit (in a technical or design sense) for 1.20.1, and likely fully diverging when 1.20.2/1.21 arrives.
 
 
As for the reasons regarding the existence of NeoForged as a fork of Forge, I direct people to read the blog post written by cpw, one of the founding members of NeoForge and a current permanent member of its steering council.
 
In short, the leadership of Forge, LexManos, has been problematic in their behavior and actions for a long time, and a breaking point was reached in part because of the troubling treatment of senior contributors, leaders, and members of the team, and in part due to the toxic environment nurtured over many years by aforesaid leadership.
 
Rest assured, many opportunities were taken in the past to try change and reform the environment and the leadership. However, despite all those actions proposed and implemented, and because of the ulterior motives which ultimately tainted some of those actions, little to no reform actually stuck to the wall, so to speak. A breaking point was then reached, and it was decided that reforming or defending the existing leadership was no longer viable; hence, the fork of NeoForged, with new leadership and new branding.

**Comment by Napoleon-x** [comment]
> @Napoleon-x Trolls are not welcome here.
> 
> @jdz-green Only the discord server was rebranded. The Forge project website and github repositories remain Forge. Forge has a new discord server you can join if that's what you want to do.

I appreciate your enthusiasm on maintaining a clean discourse @marchermans however you seem to have misinterpreted my comment, I for one absolutely support the idea of competition in any form, whether it be in terms of forks or whatever. You do you, right? I just think the whole reason for this was rather unwarranted and may just cause a split within the Forge community but perhaps some good may still come from this, who knows.

**Comment by Napoleon-x** [comment]
Much more fun to watch this pass by with closed eyes and a deep smile and let the enthusiasm fly 😁
