### ISSUE TITLE
Documentation for ASM field-to-method mappings in targeted class

### ISSUE THREAD

**Issue by elifoster** [neoforged/NeoForge#385]
Requesting that documentation comments be added to targeted classes in the [field to method ASM map](https://github.com/neoforged/NeoForge/blob/1.20.x/src/main/resources/coremods/field_to_method.js), for example:

```java
// in BucketItem.java

/** mapped to getFluid() by NeoForge coremod */
private final Fluid content;
```

When you're just looking at the code, it's unclear how these fields get assigned. I spent a long time today debugging, trying to figure out how buckets get the fluid to place, only to discover it's assigned through ASM. A one-line comment would have saved me all that trouble.

**Comment by sciwhiz12** [comment]
Note that this would have to be done manually, since (as far as I'm aware) we do not currently have a way to automatically insert (javadoc) comments into the source (outside of mappings data).

However, I think @Matyrobbrt and @shartte have been collaborating into bringing in https://github.com/neoforged/Javadoctor into our toolchain, which would allow combining sources of javadocs and inserting them programmatically...?
