### ISSUE TITLE
Regression with Pick Block on Frosted Ice: MC-90601

### ISSUE THREAD

**Issue by Lolothepro** [neoforged/NeoForge#418]

**Comment by covers1624** [comment]
Was this previously fixed? What version did it regress?
Does this occur in vanilla?
What versions have you tested?

Do you have _any_ information to help investigate the issue? Logs? Screenshots? Cat pictures?

**Comment by Lolothepro** [comment]
> Was this previously fixed? What version did it regress? Does this occur in vanilla? What versions have you tested?
> 
> Do you have _any_ information to help investigate the issue? Logs? Screenshots? Cat pictures?

This bug has been fixed in Minecraft 15w49a, but still occurs in NeoForge (the latest version).

**Comment by Lolothepro** [comment]
![image](https://github.com/neoforged/NeoForge/assets/68275908/d4c7dc6d-782f-4072-9903-70da212a4dd7)

**Comment by covers1624** [comment]
'The latest version' is very unhelpful. Please provide the exact version you have tested with.

**Comment by Lolothepro** [comment]
> 'The latest version' is very unhelpful. Please provide the exact version you have tested with.

NeoForge 20.4.52-beta

**Comment by sciwhiz12** [comment]
@Lolothepro, multiple times over the course over the past few weeks you have consistently provided issue reports which lacked information or context, disregarding the issue report template we provide.

While we acknowledge your efforts in reporting issues for triaging and fixing, it is quite frustrating that we need to continually ask you for further information in your reports which are specified in the issue report template.

**Do better, please.** Start following the issue report template. Give additional context to issues. Describe issues with words rather than simply show pictures and/or videos. For vanilla issue reports on Mojira, provide links and summaries of those bug reports.

If you are unable to follow these simple steps, after all these weeks/months, we will have to take corrective action by temporarily revoking your access to file issues until you make a strong commitment to us that you will follow the template as written.

**Comment by Lolothepro** [comment]
[latest.log](https://github.com/neoforged/NeoForge/files/13759783/latest.log)

**Comment by Lolothepro** [comment]
> @Lolothepro, multiple times over the course over the past few weeks you have consistently provided issue reports which lacked information or context, disregarding the issue report template we provide.
> 
> While we acknowledge your efforts in reporting issues for triaging and fixing, it is quite frustrating that we need to continually ask you for further information in your reports which are specified in the issue report template.
> 
> **Do better, please.** Start following the issue report template. Give additional context to issues. Describe issues with words rather than simply show pictures and/or videos. For vanilla issue reports on Mojira, provide links and summaries of those bug reports.
> 
> If you are unable to follow these simple steps, after all these weeks/months, we will have to take corrective action by temporarily revoking your access to file issues until you make a strong commitment to us that you will follow the template as written.

I hadn't used the templates because I wanted to modify the bug report, and just add the Vanilla bug report on a screenshot, as everything was already detailed on it.
by the way, I don't see the point of writing the tested version of NeoForge, since to make a bug report, it's necessary to use the latest version of NeoForge, because it's possible that the bug is fixed in more recent versions.

**Comment by KnightMiner** [comment]
The latest version is constantly changing, and many people don't use the latest when testing. You reporting the version is confirmation that you actually used that version.

Also, you were asked to follow the template. It does not matter if you agree with the template, follow it because you were asked to and it makes less work for triage

**Comment by sciwhiz12** [comment]
> I hadn't used the templates because I wanted to modify the bug report, and just add the Vanilla bug report on a screenshot, as everything was already detailed on it.

You can modify the template, but erasing wholesale the contents of the template and then only attaching a mere _screenshot_ of the vanilla bug report _after_ being prompted to do so is subpar issue reporting.

> by the way, I don't see the point of writing the tested version of NeoForge, since to make a bug report, it's necessary to use the latest version of NeoForge, because it's possible that the bug is fixed in more recent versions.

The purposes of including the NeoForge version in the issue report are varied: 
- It reminds the issue reporter to check what version of NeoForge they are testing (if they're on an outdated version);
- It ensures the issue reporter, the issue triager, and all other viewers are on the same page on what NeoForge version was tested;
- It records what version experienced the issue being reported at the time it was reported;
- It avoids having issue triager/viewers needing to ask for the version.

The issue template and its contents exist _for a reason_; it wasn't done on a whim to make the lives of reporters and developers more difficult or annoying.

**Comment by Lolothepro** [comment]
Can't you just improve the template? The template of all modloaders is always weird... unlike the template of mods which is much better.
and even separate the template for bug reports from developers and ordinary users.

**Comment by Lolothepro** [comment]
ie:
CaffeineMC template:
![image](https://github.com/neoforged/NeoForge/assets/68275908/a035945e-0246-4402-a827-e9ae0900e65f)

**Comment by sciwhiz12** [comment]
Certainly, we can improve the issue template and we welcome suggestions and PRs to improve it. (We've been focused on trying to improve the code itself for the past few months, so we haven't gotten much time or manpower to improve non-code areas of NeoForge.)

However, that isn't a reason or excuse to disregard the point of the issue template, which is to provide a minimum amount of information about the report in the initial report message itself, instead of needing to do a back-and-forth between reporter and developer on the environmental and contextual information.

Also, consider the fact that mods often get a larger volume of issue reports from end-users, from new (who may be new to GitHub!) to the experienced, while modloaders such as NeoForge usually get reports from seasoned end-users and mod developers who have used GitHub for a while. There's a certain expectation that those who report issues here know at least basic troubleshooting concepts, such as providing as much relevant information as can be given without needing to be prompted manually.

**Comment by covers1624** [comment]
I can confirm this issue is NOT present on Vanilla `1.20.4` and is present as far back as Neo `20.4.0-beta`.

@XFactHD and I have pinned the likely cause to this patch hunk: <https://github.com/neoforged/NeoForge/blob/1.20.x/patches/net/minecraft/client/Minecraft.java.patch#L432-L436> Which appears to be roughly identical all the way back to 1.19+.

**Comment by Lolothepro** [comment]
> Certainly, we can improve the issue template and we welcome suggestions and PRs to improve it. (We've been focused on trying to improve the code itself for the past few months, so we haven't gotten much time or manpower to improve non-code areas of NeoForge.)
> 
> However, that isn't a reason or excuse to disregard the point of the issue template, which is to provide a minimum amount of information about the report in the initial report message itself, instead of needing to do a back-and-forth between reporter and developer on the environmental and contextual information.
> 
> Also, consider the fact that mods often get a larger volume of issue reports from end-users, from new (who may be new to GitHub!) to the experienced, while modloaders such as NeoForge usually get reports from seasoned end-users and mod developers who have used GitHub for a while. There's a certain expectation that those who report issues here know at least basic troubleshooting concepts, such as providing as much relevant information as can be given without needing to be prompted manually.

Okay, but can you improve the template? 🥺
