### ISSUE TITLE
Patch in extensible support for Boat$Type

### ISSUE THREAD

**Issue by Tslat** [neoforged/NeoForge#491]
Boats are currently 90% of the way doable in terms of modded additions without requiring a whole new entity and the like

The vast majority of this remaining gap can be resolved by making Boat.Type an extensible enum.

The only things remaining from there would be to figure out how to properly redirect the `getDropItem` methods in Boat and ChestBoat, since they're just a static enum switch

Ideally this should be done before going to stable, as people who did a big silly and made an enum switch for a boat without a default statement might be inexplicably unsafe after this change

**Comment by XFactHD** [comment]
This is significantly more involved than just making the `Boat.Type` enum extensible, mainly because the type of a boat is synced as an integer and the ordinals of the modded entries would therefore need to match between server and client, which simply making the enum extensible cannot guarantee. The drop item issue is comparatively simple to solve.

With that said, since I was curious, here's a functional prototype which shows the rather significant surface of this change: https://github.com/XFactHD/NeoForge/commit/04013fa6d897abd1701ad697d3b5e71d9cd5fc8f. It currently just has one significant annoyance, that being a circular dependency between the boat items and the boat type.
