### ISSUE TITLE
Patch `BlockEntityType#validBlocks` to be mutable

### ISSUE THREAD

**Issue by Tslat** [neoforged/NeoForge#494]
Currently there's no neat way to add modded blocks to vanilla BlockEntityTypes, requiring users to mixin/reflect into various places, often very inefficiently or in unstable manners, to support custom signs, etc.

This is easily fixed by just introducing a patch to add to the `ImmutableSet<Block>` that is currently holding the valid blocks for the BE type.
Literally any way you achieve this is fine.

**Comment by Technici4n** [comment]
Would it not be preferable to create new modded block entity types? I have no idea how safe it is to modify existing block entity types, I suppose it could mess with registry syncing.

**Comment by Tslat** [comment]
> Would it not be preferable to create new modded block entity types? I have no idea how safe it is to modify existing block entity types, I suppose it could mess with registry syncing.

I don't see why it would be preferable
One single patch and they can be instantly supported instead of needing to make a whole new be type, and immediately kill any compatibility with the existing BE

Why make a whole new sign blockentity type when you could just.. be a sign

As for registry syncing - Would it? BE blocks aren't synced at all - they're purely an artifact of registry-time instantiation

**Comment by marchermans** [comment]
This is not really something i would like to support.

What are your justifications for such an invasive change?
If you want to add your own block, then make a new bet, if you want to add a third party block to a third party bet then I am not sure that is a route that i want to enable, since this can have major unforeseen consequences.

**Comment by Tslat** [comment]
Cool, I'll just keep doing it myself via mixin then, having had literally no issues ever doing it this way

I have absolutely no idea what consequences you think could come of this, but if that's how it's seen then so be it

**Comment by Matyrobbrt** [comment]
For the record https://github.com/MinecraftForge/MinecraftForge/pull/9039

**Comment by Technici4n** [comment]
I think this feature can be quite useful and doesn't require much maintenance on our end.

**Comment by TelepathicGrunt** [comment]
> I am not sure that is a route that i want to enable, since this can have major unforeseen consequences.

@marchermans Please give specific examples of consequences. Being vague doesn’t help when trying to figure out if this is good to support or not.

**Comment by marchermans** [comment]
> > I am not sure that is a route that i want to enable, since this can have major unforeseen consequences.
> 
> @marchermans Please give specific examples of consequences. Being vague doesn’t help when trying to figure out if this is good to support or not.

I am primarly worried about Block and BlockEntity pairs expecting the other block or blockentity to be exactly where the implementer expects this. The issue maty mentioned above, mentions the usecase being extending vanilla block entities. I personally indeed see a usecase here, but I have a very hard time seeing this in a usefull scenario for modded blocks.

In particular an API like this is extremely niche, and if mis-used then the issues can be extremely difficult to track down. 

For me a mixin that targets the specific BEs where this is relevant, seems more acurate, especially since the users of this niche API would be experienced modders like @Tslat and they are aware of the concequences.

But again, my worry is hypothetical, and if a good API is designed that prevents ab- or mis-use and if said API logs the changes requested, so not a simple: Make list editable, but something that keeps track of what is added and what not. Then I think this can be done.

**Comment by thedarkcolour** [comment]
Any updates on this? In my mods, I've always AT'd the field and replaced it with a copy containing my added values.

**Comment by thomasglasser** [comment]
Instead of simply making the list mutable, which I suppose could be abused, wouldn't adding an event to register blocks to a BE work? Prevents manual tampering with the list when they just call `event.register(BlockEntityType.SIGN, MY_SIGN.get());` and Neo handles the mutating. I'm not sure what hypothetical worries you have but I don't see any with a system like this.
