### ISSUE TITLE
Right-clicking on a sheep without wool with shears still triggers the hand animation.

### ISSUE THREAD

**Issue by Lolothepro** [neoforged/NeoForge#606]
**NeoForge Version:** 20.4.148-beta

**Steps to Reproduce:**
 1. Right-click on a sheep without wool with shears in Minecraft Vanilla
 2. Right-click on a sheep without wool with shears with NeoForge
 3. Compare

**Description of issue:**
Right-clicking on a sheep without wool with shears still triggers the hand animation.

**Video:**

NeoForge:

https://github.com/neoforged/NeoForge/assets/68275908/9cf8b0ae-c85f-427a-a175-ea89b7272b3b

Vanilla:

https://github.com/neoforged/NeoForge/assets/68275908/866c7de0-7fc6-4ba1-9a34-35021eab5fd1

**Comment by sciwhiz12** [comment]
This appears to be an old bug that predates NeoForge. Minecraft Forge 1.19.4-45.2.8 is affected by this bug as well.

The root cause, as I understand it, is due to the logical structure of the [patch in `ShearsItem`](https://github.com/neoforged/NeoForge/blob/c21ccd2ac7c341f98b2d65bc789e0bf439449a94/patches/net/minecraft/world/item/ShearsItem.java.patch) which is used for the `IShearable` interface. The shearability test (the `isShearable`) and the return value are independent of each other; as long as the target entity is `IShearable` (like a sheep, or a snow golem), the return value will be `SUCCESS` or `CONSUME` (depending on the side), which means the player hand will swing.

The fix should be to combine the two returns for `SUCCESS` and `CONSUME` into one return at the end of the innermost `if` (and using `InteractionResult#sidedSuccess`, as other overrides of `interactLivingEntity` do), when the shearability test succeeds. However, that would cause `isShearable` to be called on both server-side and client-side, which might have unintended side-effects.

@pupnewfster, given your work on the shearing patches at #581, do you think we should push through with this fix? (Others are welcome to comment as well.)

**Comment by pupnewfster** [comment]
I think it is a reasonable change, though it may be something we want to wait until 1.20.5 with and then  while fixing it also restructure parts of our shareable to be more of an extension interface. At which point we can also safely put what sides it is safe to be called on as part of the javadocs.

That all being said we could also temporarily patch it by for client side instance check if it is also vanilla's Shearable interface and then return a result on the client based on that result.
