### ISSUE TITLE
Some entities' AI seems slightly broken (the entities move and spin)

### ISSUE THREAD

**Issue by Lolothepro** [neoforged/NeoForge#647]
**NeoForge Version:** 20.4.167

**Steps to Reproduce:**
 1. Load the world here: [Tets.zip](https://github.com/neoforged/NeoForge/files/14363882/Tets.zip)
 2. Take a hay bale
 3. Compare AI (path finding) behavior between NeoForge and Minecraft Vanilla

**Description of issue:**
(the entities move and spin on themselves)

NeoForge:

https://github.com/neoforged/NeoForge/assets/68275908/5139007e-8d86-4ca9-8188-e20c5b45481a

https://github.com/neoforged/NeoForge/assets/68275908/b44712fa-3bbb-4490-a9ab-6bed6bc40cd6

Vanilla:

https://github.com/neoforged/NeoForge/assets/68275908/86e593cb-d115-4034-96a3-06c11c60e4b1

**Comment by embeddedt** [comment]
Likely to be one of the patches in https://github.com/neoforged/NeoForge/tree/1e168a9fd77b10e62a0c66874939ebcb832b1af7/patches/net/minecraft/world/entity/ai/navigation, didn't look any further though.

**Comment by embeddedt** [comment]
Applying the cast fix in https://github.com/MinecraftForge/MinecraftForge/pull/6455 fixes the issue of the llama spinning while I stand still. However, it still sometimes changes direction unnecessarily when trying to walk to me. Ideally someone with more experience in this area should determine if that remaining side effect is expected behavior.
