### ISSUE TITLE
Installers for 1.20.2 and 1.20.4 (below .185) not working

### ISSUE THREAD

**Issue by sciwhiz12** [neoforged/NeoForge#671]
All **installers for NeoForge versions below `20.4.185` are currently broken** (including installers for 1.20.2.)

We have fixed the installer issue for `.185` and onwards, and will be working towards fixing all old installers within a week.

The issue was caused due to a combination of a now-retired domain being checked by the installer, and an oversight in the installer code causing a crash when the domain returns nothing.

**Comment by AlfatArdiansa** [comment]
No fix yet. But I have a solution while waiting for the NeoForge developers to fix it.
If you use a Windows device:
Open `C:\Windows\System32\drivers\etc\hosts` with a notepad and append this at the bottom of the file 
`13.107.246.59 authserver.mojang.com`

`13.107.246.59` is the IP of `sessionserver.mojang.com` which is a new domain for `authserver.mojang.com`

For linux user i believe there is `hosts` file under the `/etc` directory just add the same line like windows does("I'm not so sure about my memory"). It's been a long time since I last used Linux.

**Comment by Matyrobbrt** [comment]
All installers for 1.20.1, 1.20.2, 1.20.3 and 1.20.4 have been patched. If you're still experiencing the issue, make sure to prune your local caches.
