### ISSUE TITLE
Component.translatable crashes for non component/number/string objects.

### ISSUE THREAD

**Issue by Raycoms** [neoforged/NeoForge#703]
Orion told me to open it as a ticket.

Atm a Component.translatable crashes with most objects that are neither components nor basic primitives.

I do agree that people shouldn't put random objects in there and instead either do .toString themselves or use the translatableEscape method.

But, I believe a lot of mods don't even know about this and the crashes are also in a way that makes it very hard to find the origin code.

Request is: Don't crash but throw a warning with stracktrace.

**Comment by sciwhiz12** [comment]
There is the potential here, if we go ahead with the suggestion of making the method do the operation itself and logging a warning, that the warnings go unheeded and modders go ahead with using the method in that way.

It is an understood phenomenon currently that mods often fill up logs with many warnings due to their use of methods or features that emit those warnings, but which go unheeded by developers and therefore take up space in logs. Among other things, this causes a lot of warning fatigue, where people stop looking into the warnings because of their sheer quantity.

That observation is in part why there's been a slow shift over time from simply emitting warnings to making things crash in development -- because developers often are not motivated to fix warnings unless they present actual crashes.

---

As I understand it, this crash happens when the networking code tries to (de)serialize the component, including its arguments, and being unable to handle non-standard arguments (i.e., primitives, other `Component`s).

An alternative here would be to make the `translatable` methods (or rather, the constructor for `TranslatableContents`) crash with a legible stacktrace if a mod creates a component with non-escaped arguments. That way, modders are still forced to reckon with the consequences of using that method (and therefore are incentivized to fix it), we _technically_ preserve vanilla behavior in a way (since it would've crashed anyway), and we avoid possible warning logspam.

**Comment by Raycoms** [comment]
It's fine to crash in dev, just shouldn't crash in prod tbh.
