### ISSUE TITLE
[20.5] Closing options screen unpauses the game

### ISSUE THREAD

**Issue by ApexModder** [neoforged/NeoForge#861]
**Minecraft Version:** 1.20.5

**NeoForge Version:** 20.5.5-beta

**Steps to Reproduce:**
 1. Load any world with neoforge installed
 2. Pause the game and goto the options screen
 3. Click done button
 4. Watch how the game is unpaused and your not taken back to the "pause" screen

**Description of issue:**
Closing the options menu unpauses the game rather than redirecting back to the pause screen

![java_Dg1U5tdTOr](https://github.com/neoforged/NeoForge/assets/29412632/0df8dccf-cd41-45a0-834a-5ce53384f4e9)

**Comment by embeddedt** [comment]
Didn't look into it much, but at first glance this appears to be an intentional patch? https://github.com/neoforged/NeoForge/blame/961d18f36978ae41273140ec2ba4b28dca1583d4/patches/net/minecraft/client/gui/screens/OptionsScreen.java.patch#L8

The patch originates from https://github.com/MinecraftForge/MinecraftForge/pull/6682, apparently they were trying to make ESC and pressing Done have consistent behavior.

**Comment by ApexModder** [comment]
I mean it is consistent behavior pressing ESC does the same thing, directly unpauses the game rather than going to the "pause" screen

**Comment by sciwhiz12** [comment]
From testing, the following are the results from hitting the Escape key versus clicking the Done button on the Options screen across four different Minecraft instances:

| Instance description | Escape key | Done button |
|-|-|-|
| Vanilla 1.15.2 | Exit to in-game | Return to in-game menu |
| Forge 1.15.2 (31.2.57) | Return to in-game menu | Return to in-game menu |
| Vanilla 1.20.5 | Return to in-game menu | Return to in-game menu |
| NeoForge 1.20.5 (20.5.5-beta) | Exit to in-game | Exit to in-game |

We can infer the original intention of the PR was to harmonize the behaviors of the Escape key and the Done button on the Options screen to returning to the previous screen which, based on the results above, was to return to the in-game pause menu.

Based on this information, we can conclude that the patches are now faulty, and should be removed in order to restore the vanilla behavior of returning to the in-game menu for both both Escape key and Done button.
