### ISSUE TITLE
[Feature Req] add yarn/ fabric compatibility

### ISSUE THREAD

**Issue by SadisticLoli** [neoforged/NeoForge#88]
as simple as that. i want to see both fabric and neoforge to stop barking at each other.. now that the project is under new (hopefully) Non monopolized management.

**Comment by TheCurle** [comment]
Compatibility with Fabric is not feasible - that basically means that either Fabric or Forge completely cease to exist, which neither we nor Fabric want to happen.

We are already compatible with Yarn, because of the extensible nature of ForgeGradle, and the ability to use alternative toolchains like Loom.
