### ISSUE TITLE
[1.20.5] Creative Menu Enchanted Books are not ordered correctly.

### ISSUE THREAD

**Issue by ChrysanthCow** [neoforged/NeoForge#886]
**Minecraft Version:** 1.20.5

**NeoForge Version:** 20.5.20-beta

**Logs:** https://mclo.gs/CnYMmRU

**Steps to Reproduce:**
 1. Open up the creative menu.
 2. View as all max levels are before all other levels that should be before it.
 
**Description of issue:**
![javaw_hGKiWH49Qm](https://github.com/neoforged/NeoForge/assets/81167232/c20a9f8a-77f2-4f73-8aaa-ce0031d33055)

Creative Menu Books are ordered incorrectly in that all maximum levels of enchantment will be ordered before any other level of enchantment.

Vanilla behavior would have this as it was before.

**Comment by ChrysanthCow** [comment]
I've just put the logs in to show that I have no mods causing this issue.

**Comment by embeddedt** [comment]
This also appears to happen in 1.20.1. It is likely caused by our patched creative mode tab building logic, as there is a comment referencing this behavior:

https://github.com/neoforged/NeoForge/blob/85bc0fe799dad4395a1e36e072c2ccaf1e95bfb2/src/main/java/net/neoforged/neoforge/event/EventHooks.java#L969-L977

The merging likely causes the original ordering from the vanilla code to be lost, since it presumably retains the first added key (which would be the max level book, rather than the level 1 book).
