### ISSUE TITLE
PlayMessages.OpenContainer swallows exceptions during screen construction

### ISSUE THREAD

**Issue by Shadows-of-Fire** [neoforged/NeoForge#92]
Any exceptions thrown during the construction of a screen will be ignored entirely, and the screen will fail to open.
This is due to the following `try/finally` block not having a `catch` block, which causes the exception to vanish.
https://github.com/neoforged/NeoForge/blob/1.20.x/src/main/java/net/minecraftforge/network/PlayMessages.java#L297

**Comment by Technici4n** [comment]
The exception is propagated if there is no `catch` block, it doesn't just stop. You can probably see the exception in the logs.

**Comment by Shadows-of-Fire** [comment]
Errors thown are not propagated (they do not crash or log an error) - I'm not sure _where_ they end up, nor am I actually certain if the lack of a catch block there is to blame.

It might be deeper in that the exception is getting swallowed.

**Comment by XFactHD** [comment]
From a quick test, this doesn't appear to be an issue anymore in 1.20.2. As a test I rigged up the anvil to use `NetworkHooks.openScreen()` instead of `Player#openMenu()` and added `if (true) throw new UnsupportedOperationException()` to the anvil screen constructor. Upon right clicking the anvil, the stacktrace is logged. If I use a `Throwable` that doesn't extend `Exception` (i.e. `ExceptionInInitializerError` - first one I could think of for some reason), then it crashes the game entirely because neither the catch in `PacketUtils.ensureRunningOnSameThread()` nor the one in `BlockableEventLoop#doRunTask()` catches these. If I do the same thing in a 1.20.1 environment (with a custom screen in this case), then neither variant logs or crashes.

I have yet to fully grasp why this is the case but my best guess is that it has to do with the timing of when modded payloads (which includes the `PlayMessages.OpenContainer` packet) are pulled out of the vanilla code path. In 1.20.1 this happens at the head of `ClientPacketListener#handleCustomPayload()` before the `PacketUtils.ensureRunningOnSameThread()` call and therefore on the network thread. In 1.20.2 it happens in `ClientPacketListener#handleUnknownCustomPayload()` which is after the `PacketUtils.ensureRunningOnSameThread()` (located in `ClientCommonPacketListener#handleCustomPayload()`) and therefore on the main thread.

**Comment by Matyrobbrt** [comment]
This is definitely fixed since 84550f277d2fcdede305580685924a47387cf8c4 (followed by acab30d512e2854d01f8c4539567d1ef85ba178a), as there is now an explicit catch with logging and that disconnects the player.
