### ISSUE TITLE
NeoForge Benefits

### ISSUE THREAD

**Issue by med1coo** [neoforged/NeoForge#982]
Hey,

Since there is absolutely no information on the website or on GitHub, what are the benefits of NeoForge compared to Forge?

**Comment by TelepathicGrunt** [comment]
@med1coo the answer depends on what you’re specifically looking for. Are you a player looking for stuff that makes player experiences better? Are you a modder looking for what makes the modding experience better? Performance? Stability? Leadership?

**Comment by CodexAdrian** [comment]
Hi o/. In my experience, using NeoForge as a developer has been a really pleasant experience. The devs are alot more open to making changes and improvements on decades old APIs and have already accepted many such improvements. Things like the capability system were overhauled on NeoForge and are a huuuge improvement over the old system forge still uses that makes forge hard to go back to. In fact, the capability system is more capable now than it was before, as it was not possible to use capabilities on blocks without block entities. Data attachments are also a massive improvement over the way forge used to handle custom serialization of data. They are much more intuitive and are in line with the new component system vanilla introduced, making it quite simple for devs to seamlessly support them. It is quite trivial now to attach data onto any kind of object, in a way that forge just hasn't caught up with. The Neo team just also seems to be much more attuned with what the community wants. The Forge team has been making quite a few anti-modder decisions seemingly out of stubbornness. The removal of capabilities from items in favor of grossly misusing components, the plan to remove mixins from being bundled into forge, the refusal to adapt how its networking works simply because other modloaders have already done so and more. It all speaks to a lack of judgement that makes it hard to trust that the forge lead dev can look beyond their own stubborn beliefs in order to make decisions that actually improve the loader.

**Comment by Shadows-of-Fire** [comment]
I think Adrian's response is fairly comprehensive; if you have any additional questions you can reply here or reach out on discord.
